name: WordChanger
main: WordChanger\Main
version: 1.0.1
api: [2.0.0]
author: MCPEPIG
permissions:
  wordchanger:
    default: op
    description: "Allow using all WordChanger features"
    children:
      wordchanger.override:
        default: op
        description: "Allow overriding word changes"
